config/routes.rb
Rails.application.routes.draw do
  root to: 'maps#root'
  get 'maps/select' => 'maps#show'
  get 'reviews/count'
  post 'search' => 'finds#search'
  get 'finds/show'
  post 'reviews/count'
  post 'sites/delete'
  post 'comments/delete'
  resources :maps do
    resources :sites do
      resources :comments do
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :site
  has_one :review ,dependent: :destroy
  default_scope { order(created_at: :desc) }
  validates :content, length: {maximum:240}, presence: true
end

app/models/key.rb
class Key < ApplicationRecord
  belongs_to :review
  validates :value, uniqueness:{ scope: :review_id }, presence: true
end

app/models/map.rb
class Map < ApplicationRecord
  has_secure_password
  has_many :sites ,dependent: :destroy
  default_scope { order(name: :asc) }
  validates :name, uniqueness: true, presence: true
  validates :password, presence: true,length:{minimum:6,maximum:20}
  validates :creater, length:{maximum:40}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :comment
  has_many :keys, dependent: :destroy
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :map
  has_many :comments, dependent: :destroy
  default_scope { order(created_at: :asc) }
  validates :name, presence: true
  validates :latitude, presence: true, uniqueness:{ scope: [:longitude] }
  validates :longitude, presence: true, uniqueness:{ scope: [:latitude] }
  validates :title, presence: true,length:{maximum:200}, on: :update
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def delete
    @comment = Comment.find(params[:id])
    @site = Site.find(@comment.site.id)
    @map = Map.find(@comment.site.map.id)
    if @map.authenticate(params[:password])
      @comment.destroy
      respond_to do |format|
        format.js{render :delete}
        format.html{render partial: "comments/index",locals: {
          site:@site,comments:@comments,review:@review}}
      end
    else
      respond_to do |format|
        format.js{render :password_error}
      end
    end
  end

  def new
    unless params[:id]
      @site = Site.find(params[:site_id])
    else
      @site = Site.find(params[:id])
    end
    @map = Map.find(@site.map.id)
    @comment =@site.comments.build
    respond_to do |format|
      format.js{render :index}
      format.html{render partial: "comments/new",locals: { site:@site, map:@map, comment:@comment, review:@review }}
    end
  end

  def create
    @site = Site.find(params[:site_id])
    @map = Map.find(@site.map.id)
    @comment = @site.comments.build(comment_params)
    if @comment.invalid?
      respond_to do |format|
        format.js{render :validation_error and return}
      end
    else
      @comment.save
      @review = Review.new(comment_id: @comment.id)
      @review.save
      respond_to do |format|
        format.js{render :index and return}
        format.html{render partial: "comments/index",locals: { site:@site ,comments:@site.comments}}
      end
    end
  end
  private
  def comment_params
    params.require(:comment).permit(:content,:site_id)
  end
end

app/controllers/finds_controller.rb
class FindsController < ApplicationController

  include GoogleSearch

  def search
    @map = Map.find(params[:map_id])
    @site = @map.sites.build
    # 入力フォームバリデーションチェック
    @search = InputForm.new(params.permit(:place))
    if @search.invalid?
      redirect_to map_path(@map) and return
    end
    filtered_results = GoogleSearch.search_spot(params[:place])
    @sites_composed = filtered_results.first(9).map do |site|
      {
        lat: site.lat,
        lng: site.lng,
        name: "fas fa-search fa-3x faa-flash animated",
        display_name: site.name
      }
    end
    # 検索で見つからなかった場合
    if @sites_composed.empty?
        redirect_to map_path(@map) and return
    end
    # 配列の並びを地点登録時と合わせるための処理
    @sites_composed.push({name:"",display_name:"null",lat:0,lng:0})

    respond_to do |format|
      format.html{redirect_to controller: 'finds', action: 'show' ,locals: {site: @site,map: @map,sites_composed: @sites_composed}}
    end
  end

  def show
    @map = Map.find(params[:locals][:map])
    @site = @map.sites.build
    @sites_composed = params[:locals][:sites_composed]
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def root; end

  def index
    @map = Map.new
    @maps = Map.select(:id,:name)

  end

  def show
    @maps = Map.select(:id,:name)
    if params[:id] == ""
      flash.now[:notice] = "マップを選んでください"
      render :index
    else
      @map = Map.find(params[:id])
      @site = @map.sites.build
      site_setting
      @sites_composed = compose(@sites)
    end
  end

  def site_setting
    @sites = @map.sites
  end

  def compose(sites)
    sites.map do |site|
    {lat: site.latitude,
    lng: site.longitude,
    name: site.name,
    id: site.id,
    map_id: site.map.id
    }
    end
  end

  def new
    @map = Map.new
  end

  def create
    @map = Map.new(map_params)
    if @map.save
      flash[:notice] = "マップを作成しました"
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def map_params
    params.require(:map).permit(:name,:password,:password_confirmation,:creater)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def count
    @comment = Comment.find(params[:comment_id])
    @review = Review.find(@comment.review.id)
    @site = Site.find(@comment.site.id)

    if params[:key] == "good"
      @review.increment(:good)
      @key = Key.new(value: session[:session_id])
      @key.review_id = @review.id
    elsif params[:key] == "bad"
      @review.increment(:bad)
      @key = Key.new(value: session[:session_id])
      @key.review_id = @review.id
    end

    if @key.invalid?
      respond_to do |format|
        format.js{render :validation_error}
      end
    else
      @review.save
      @key.save
      respond_to do |format|
        format.js{render :show}
        format.html{render partial: "comments/index",locals: {
          site:@site,comments:@comments,review:@review}}
      end
    end
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  def delete
    @site = Site.find(params[:id])
    @map = Map.find(params[:map_id])
    if @map.authenticate(params[:password])
      @site.destroy
      redirect_to map_path(@map)
    else
      render file: "#{Rails.root}/public/password_error.html.erb", layout: false, status: 401
    end
  end

  def create
    @map = Map.find(params[:map_id])
    @site = @map.sites.build(site_params)
    if @site.save
      redirect_to map_path(@map)
    elsif @site.latitude == nil || @site.longitude == nil
      redirect_to map_path(@map)
    else
      render file: "#{Rails.root}/public/500.html", layout: false, status: 500
    end
  end

  def show
    @site = Site.find(params[:id])
    @map = Map.find(@site.map_id)
    @comment = @site.comments.build
    @comments = @site.comments
    respond_to do |format|
      format.js{render :index}
      format.html{render partial: "sites/show",locals: { site:@site }}
    end
  end

  def update
    @site = Site.find(params[:id])
    @map = Map.find(@site.map_id)
    @site.update(site_params)
    if @site.invalid?
      respond_to do |format|
        format.js{render :validation_error and return}
      end
    end
    respond_to do |format|
      format.js{render :update_site and return}
      format.html{render 'maps/show'}
    end
  end

  private
  def site_params
    params.require(:site).permit(:name,:latitude,:longitude,:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "uri"

  def url_to_link(text)
    text.gsub!(/\n/, '<br/>')
    text.gsub!(/[[:space:]]/, '<br/>')
    URI.extract(text, ['http','https'] ).uniq.each do |url|
      sub_text = ""
      sub_text << "<a href=" << "\"" << url << "\"" << " target=\"_blank\">" << url << "</a>"
      text.gsub!(url, sub_text)
    end
    return text
  end
end

app/views/comments/_error_message.html.erb
<%= t('maps.error_message') %>

app/views/comments/_index.html.erb
  <% define_check = defined? site %>
  <% unless define_check.nil?%>
    <% site.comments.each do |comment|%>
      <% unless comment.id.nil? %>
        <div id = "comment_show">
          <h3><%= sanitize url_to_link("#{comment.content}") %></h3>
          <h5><%= time_ago_in_words(comment.created_at)+t('maps.time_before') %></h5>
          <div id = "reviews_show">
            <div class = "review">
              <%=link_to(content_tag(:i,"",class:"far fa-thumbs-up"),reviews_count_path(key: :good, comment_id: comment), method: :post,remote: true, title: "thumbs",class: "thumbs")%>
            </div>
            <div class = "review vote">
              <%=comment.review.good%>
            </div>
            <div class = "review">
            </div>
            <div class = "review">
              <%=link_to(content_tag(:i,"",class:"far fa-thumbs-up fa-flip-vertical"),reviews_count_path(key: :bad, comment_id: comment), method: :post,remote: true, class: "thumbs")%>
            </div>
            <div class = "review vote">
              <%=comment.review.bad%>
            </div>
            <div class = "review">
              <%=form_with(url:comments_delete_path,remote:true) do |f|%>
                <%=f.submit(t('maps.delete'),class:"admin_button",data:{confirm: "削除しますか"})%>
                <%=f.hidden_field :id,value:comment.id %>
                <%=f.hidden_field :map_id,value:comment.site.map.id %>
                <%=f.password_field :password ,placeholder: t('maps.password'),size: "9"%>
              <% end %>
            </div>
          </div>
        </div><hr/>
      <% end %>
    <% end %>
  <% end %>

app/views/comments/_message.html.erb
<% @comment.errors.full_messages.each do |msg| %>
  <ul>
    <%= msg %>
  </ul>
<% end %>

app/views/comments/_new.html.erb
<div id="comments_new">
  <% define_check = defined? site %>
  <% unless define_check.nil? %>
    <%= form_with(model:[map,site,comment],remote:true,method: :post) do |form| %>
      <div id="comment_field">
        <%= form.label :content, t('maps.input_comment') %>
        <%= form.text_area :content, size: "30x4", placeholder: t('maps.within_240_characters')%>
        <%= form.submit t('maps.comment'),class: "submit_btn"%>
      </div>
    <% end %>
    <div id = "reviews_validation"></div>
  <%  end %>
</div>

app/views/comments/delete.js.erb
if(typeof jQuery != "undefined"){
$(function(){

  $("#comments_index").html("<%= j(render 'comments/index', {site:@site}) %>");

  $('#sites_validation').html("");

  $('#reviews_validation').html("");

  $('#notice_message').html("<%= j(render 'layouts/infomation') %>");

  $("textarea").val("");
  });
}

app/views/comments/index.js.erb
if(typeof jQuery != "undefined"){
$(function(){

  $("#comments_index").html("<%= j(render 'comments/index', {site:@site}) %>");

  $('#sites_validation').html("");

  $('#reviews_validation').html("");

  $('#notice_message').html("<%= j(render 'layouts/notice') %>");

  $("textarea").val("");
  });
}

app/views/comments/password_error.js.erb
if(typeof jQuery != "undefined"){
  $(function(){
    
    $('#notice_message').html("<%= j(render 'error_message') %>");
    
    $('#reviews_validation').html("");

    $("textarea").val("");
    });
  }

app/views/comments/validation_error.js.erb
if(typeof jQuery != "undefined"){
  $(function(){
    $('#sites_validation').html("");
    
    $('#notice_message').html("");
    
    $('#reviews_validation').html("<%= j(render 'message') %>");

    $("textarea").val("");
    });
  }

app/views/finds/show.html.erb
<div class="my_map" id="my_map"><pre id='info'></pre>
<i class="fa fa-spinner "><%= t('maps.update_now')%></i>
<%= render 'maps/map_show'%>
</div>

app/views/layouts/_infomation.html.erb
<%=t('maps.deleted')%>

app/views/layouts/_notice.html.erb
<%=t('maps.registered')%>

app/views/layouts/_right_bar.html.erb
<div id ="right_bar">
  <div>
    <div id = "right_bar_header">
      <div>
        <button href="javascript:void(0)" class="close_btn" id="close-nav">
          <i class="fas fa-times fa-3x"></i>
        </button>
      </div>
      <div id="right_bar_message">
        <h5 id="notice_message"></h5>
      </div>
    </div>
    <div id = "right_bar_head">
      <%= render 'sites/show' ,locals:{site:@site,map:@map} %>
      <%= render 'comments/new' ,locals:{site:@site,map:@map,comment:@comment} %>
    </div>
    <div id = "right_bar_bottom">
      <div id = "comments_index">
        <%= render 'comments/index',locals:{site:@site} %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Saigai info</title>
    <%= csrf_meta_tags %>
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.6.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.6.0/mapbox-gl.css' rel='stylesheet' />
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= favicon_link_tag %>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-158090122-1">
    </script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-158090122-1');
    </script>
  </head>

  <body>
    <%= render 'layouts/menu_bar' %>
    <%= render 'layouts/right_bar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'modal' %>
  </body>
</html>

app/views/maps/_map_show.html.erb
<div id='map' class = 'target' data-markers="<%= @sites_composed.to_json %>"></div>

app/views/maps/index.html.erb
<body id = "maps_index">
  <div class ="title">
    <h2><%= t('maps.select_map') %></h2>
  </div>
  <div class ="content">
    <p class = "notice"><%= notice %></p>
    <%= form_tag('/maps/select',method: :get) do %>
      <%= select_tag('id',options_from_collection_for_select(@maps,:id,:name),class:"button",include_blank:t('maps.select')) %><br>
      <%= submit_tag(t('maps.look'),class:"button",name:nil) %>
    <% end %><br><br>
    <%= button_to t('maps.back'),{controller: 'maps',action: 'root'},{method: :get,class:"button"} %>
  </div>
</body>

app/views/maps/new.html.erb
<body id = "maps_index">
  <div class ="title">
    <h2><%= t('maps.create_map') %></h2>
  </div>
  <div class ="content">
    <div class ="maps_validation">
      <% @map.errors.full_messages.each do |msg| %>
        <ul>
          <%= "※"+msg %>
        </ul>
      <% end %>
    </div>
    <table class = "table">
    <%=form_with(model:@map,local:true) do |f|%>
      <tr>
        <td><%= f.label :name %></td>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr class="password_field" data-set=<%=t('maps.necessary_to_admin')%>>
        <td><%= f.label :password %></td>
        <td><%= f.password_field :password ,placeholder: t('maps.at_least_6_characters')%>
      </tr>
      <tr>
        <td><%= f.label :password_confirmation %> &nbsp;&nbsp;&nbsp;</td>
        <td><%= f.password_field :password_confirmation,placeholder: t('maps.reenter_password') %> </td>
      </tr>
      <tr>
        <td><%= f.label :creater %></td>
        <td><%= f.text_field :creater ,placeholder: t('maps.user_definable') %></td>
      </tr>
    </table><br>
      <%= f.submit(t('maps.create'),class:"button") %><br><br>
    <% end %>
      <%= button_to t('maps.back'),{controller: 'maps',action: 'root'},{method: :get,class:"button"} %>
  </div>

</body>

app/views/maps/root.html.erb
<body id = "maps_index">
  <div class ="title">
    <h1>Saigai info</h1>
  </div>
  <div class = "content">
    <p class = "notice"><%= notice %></p>
    <%=button_to t('maps.select_map'), {controller: 'maps', action: 'index'}, {method: :get,class: "button"} %><br>
    <%=button_to t('maps.create_map'), {controller: 'maps', action: 'new'}, {method: :get,class: "button"} %><br>
  </div>
  <div id="explication">
  </div>
</body>

app/views/maps/show.html.erb
<div class="my_map"><pre id='info'></pre>
<i class="fa fa-spinner "><%= t('maps.update_now')%></i>
<%= render 'maps/map_show'%>
</div>

app/views/reviews/_message.html.erb
<% @key.errors.full_messages.each do |msg| %>
  <ul>
    <%= msg %>
  </ul>
<% end %>

app/views/reviews/show.js.erb
if(typeof jQuery != "undefined"){
  $(function(){
    $("#comments_index").html("<%= j(render 'comments/index',{site:@site})%>");

    $('#reviews_validation').html("");

    $('#notice_message').html("");
    });
  }

app/views/reviews/validation_error.js.erb
if(typeof jQuery != "undefined"){
  $(function(){
    $('#reviews_validation').html("");

    $('#sites_validation').html("");

    $('#notice_message').html("<%= j(render 'message') %>");
    });
  }

app/views/sites/_message.html.erb
<% @site.errors.full_messages.each do |msg| %>
  <ul>
    <%= msg %>
  </ul>
<% end %>

app/views/sites/_show.html.erb
<div id = "sites_show">
  <h5><%= t('maps.map_name') %> : <%=@site&.map&.name%><br><%= t('maps.map_creater') %> : <%=@site&.map&.creater%></h5>
  <% define_check = defined? site %>
  <% unless define_check.nil? %>
    <% if site.title != nil %>
      <h3><%= t('maps.site_name') %> : <%= sanitize url_to_link("#{site.title}") %></h3>
    <% else %>
      <h5><%= t('maps.name_site') %></h5>
      <%= form_with(model:@site,url:map_site_path(@site),remote: true,method: :patch) do |form| %>
        <strong><%= form.label :title, t('maps.enter') %></strong>
        <%= form.text_field :title ,size: "29"%><br>
        <%= form.submit t('maps.register'),class: "register_btn"%>
      <% end %>
    <% end %>
    <div id = "sites_validation">
    </div>
    <div class = "site_delete_field">
      <% if @site&.id != nil %>
        <% if @site != @site.map.sites.first%>
          <%=form_with(url:sites_delete_path,local:true) do |f|%>
            <%=f.submit(t('maps.site_delete'),class:"admin_button",data:{confirm: "削除しますか"})%>
            <%=f.hidden_field :id,value:@site.id %>
            <%=f.hidden_field :map_id,value:@site.map_id %>
            <%=f.password_field :password ,placeholder: t('maps.password'),size: "9"%>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/sites/index.js.erb
if(typeof jQuery != "undefined"){
  $(function(){

    $("#right_bar").scrollTop(0);

    $("#sites_show").html("<%= j(render 'sites/show',{map:@map,site:@site}) %>")

    $("#comments_new").html("<%= j(render 'comments/new',{map:@map,site:@site,comment:@comment}) %>")

    $("#comments_index").html("<%= j(render 'comments/index',{comments:@comments,site:@site}) %>")

    $('#notice_message').html("");

    $("textarea").val("");

    $('#reviews_validation').html("");

    });
  }

app/views/sites/update_site.js.erb
if(typeof jQuery != "undefined"){
  $(function(){
    $('#notice_message').html("<%= j(render 'layouts/notice') %>");

    $("#sites_show").html("<%= j(render 'sites/show',{site:@site}) %>")
    
    $("textarea").val("");

    $('#reviews_validation').html("");
    });
  }

app/views/sites/validation_error.js.erb
if(typeof jQuery != "undefined"){
  $(function(){
    $('#sites_validation').html("<%= j(render 'message') %>");

    $('#notice_message').html("");

    $("textarea").val("");

    $('#reviews_validation').html("");
    });
  }